version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: microshop-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyStrongPassword123!
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "50054:50054" 
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_TTL_SECONDS=86400
      - MYSQL_USER=root
      - MYSQL_PASSWORD=MyStrongPassword123!
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=shop
      - MYSQL_DSN=root:MyStrongPassword123!@tcp(mysql:3306)/shop?parseTime=true
      - NATS_URL=nats://nats:4222
      - GRPC_PORT=50054
      - MAILJET_API_KEY=${MAILJET_API_KEY}
      - MAILJET_SECRET_KEY=${MAILJET_SECRET_KEY}
      - MAILJET_SENDER_EMAIL=adajdzardanov@gmail.com
      - MAILJET_SENDER_NAME=CodeMart
    depends_on:
      - mysql
      - redis
      - nats
    restart: always

  redis:
    image: redis:7.0
    container_name: microshop-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes 

  nats:
    image: nats:latest
    container_name: microshop-nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222" 
    command: "--jetstream" 

volumes:
  mysql_data:
