// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapter/mailer/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapter/mailer/interface.go -destination=internal/adapter/mailer/mocks/mailer_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/RakhatLukum/CodeMart/product-service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendProductCreatedEmail mocks base method.
func (m *MockMailer) SendProductCreatedEmail(toEmail, toName string, product model.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendProductCreatedEmail", toEmail, toName, product)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendProductCreatedEmail indicates an expected call of SendProductCreatedEmail.
func (mr *MockMailerMockRecorder) SendProductCreatedEmail(toEmail, toName, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendProductCreatedEmail", reflect.TypeOf((*MockMailer)(nil).SendProductCreatedEmail), toEmail, toName, product)
}
