// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: cart.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{0}
}

func (x *Cart) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cart) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Cart) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Tags          string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type CreateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartRequest) Reset() {
	*x = CreateCartRequest{}
	mi := &file_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartRequest) ProtoMessage() {}

func (x *CreateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartRequest.ProtoReflect.Descriptor instead.
func (*CreateCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCartRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCartRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type CreateCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCartResponse) Reset() {
	*x = CreateCartResponse{}
	mi := &file_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCartResponse) ProtoMessage() {}

func (x *CreateCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCartResponse.ProtoReflect.Descriptor instead.
func (*CreateCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCartResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateCartResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCartResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemRequest) Reset() {
	*x = DeleteCartItemRequest{}
	mi := &file_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemRequest) ProtoMessage() {}

func (x *DeleteCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteCartItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCartItemRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCartItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteCartItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCartItemResponse) Reset() {
	*x = DeleteCartItemResponse{}
	mi := &file_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCartItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCartItemResponse) ProtoMessage() {}

func (x *DeleteCartItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCartItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteCartItemResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCartItemResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type UserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	mi := &file_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{6}
}

func (x *UserIDRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Carts         []*Cart                `protobuf:"bytes,1,rep,name=carts,proto3" json:"carts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartListResponse) Reset() {
	*x = CartListResponse{}
	mi := &file_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartListResponse) ProtoMessage() {}

func (x *CartListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartListResponse.ProtoReflect.Descriptor instead.
func (*CartListResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CartListResponse) GetCarts() []*Cart {
	if x != nil {
		return x.Carts
	}
	return nil
}

type CartItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Product             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemsResponse) Reset() {
	*x = CartItemsResponse{}
	mi := &file_cart_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemsResponse) ProtoMessage() {}

func (x *CartItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemsResponse.ProtoReflect.Descriptor instead.
func (*CartItemsResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{8}
}

func (x *CartItemsResponse) GetItems() []*Product {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateCartItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartItemRequest) Reset() {
	*x = UpdateCartItemRequest{}
	mi := &file_cart_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartItemRequest) ProtoMessage() {}

func (x *UpdateCartItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartItemRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCartItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCartItemRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCartItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type HasProductInCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasProductInCartRequest) Reset() {
	*x = HasProductInCartRequest{}
	mi := &file_cart_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasProductInCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasProductInCartRequest) ProtoMessage() {}

func (x *HasProductInCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasProductInCartRequest.ProtoReflect.Descriptor instead.
func (*HasProductInCartRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{10}
}

func (x *HasProductInCartRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HasProductInCartRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type HasProductInCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasProduct    bool                   `protobuf:"varint,1,opt,name=has_product,json=hasProduct,proto3" json:"has_product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasProductInCartResponse) Reset() {
	*x = HasProductInCartResponse{}
	mi := &file_cart_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasProductInCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasProductInCartResponse) ProtoMessage() {}

func (x *HasProductInCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasProductInCartResponse.ProtoReflect.Descriptor instead.
func (*HasProductInCartResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{11}
}

func (x *HasProductInCartResponse) GetHasProduct() bool {
	if x != nil {
		return x.HasProduct
	}
	return false
}

type CartItemCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItemCountResponse) Reset() {
	*x = CartItemCountResponse{}
	mi := &file_cart_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItemCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItemCountResponse) ProtoMessage() {}

func (x *CartItemCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItemCountResponse.ProtoReflect.Descriptor instead.
func (*CartItemCountResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{12}
}

func (x *CartItemCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CartTotalPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPrice    float64                `protobuf:"fixed64,1,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartTotalPriceResponse) Reset() {
	*x = CartTotalPriceResponse{}
	mi := &file_cart_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartTotalPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartTotalPriceResponse) ProtoMessage() {}

func (x *CartTotalPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartTotalPriceResponse.ProtoReflect.Descriptor instead.
func (*CartTotalPriceResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{13}
}

func (x *CartTotalPriceResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type SendCartSummaryEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToEmail       string                 `protobuf:"bytes,1,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	ToName        string                 `protobuf:"bytes,2,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCartSummaryEmailRequest) Reset() {
	*x = SendCartSummaryEmailRequest{}
	mi := &file_cart_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCartSummaryEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCartSummaryEmailRequest) ProtoMessage() {}

func (x *SendCartSummaryEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCartSummaryEmailRequest.ProtoReflect.Descriptor instead.
func (*SendCartSummaryEmailRequest) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{14}
}

func (x *SendCartSummaryEmailRequest) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *SendCartSummaryEmailRequest) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *SendCartSummaryEmailRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EmailStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailStatusResponse) Reset() {
	*x = EmailStatusResponse{}
	mi := &file_cart_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailStatusResponse) ProtoMessage() {}

func (x *EmailStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailStatusResponse.ProtoReflect.Descriptor instead.
func (*EmailStatusResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{15}
}

func (x *EmailStatusResponse) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

func (x *EmailStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResponse) Reset() {
	*x = CacheResponse{}
	mi := &file_cart_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResponse) ProtoMessage() {}

func (x *CacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cart_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResponse.ProtoReflect.Descriptor instead.
func (*CacheResponse) Descriptor() ([]byte, []int) {
	return file_cart_proto_rawDescGZIP(), []int{16}
}

func (x *CacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CacheResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cart_proto protoreflect.FileDescriptor

const file_cart_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cart.proto\x12\x04cart\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\x04Cart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\"W\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\"K\n" +
	"\x11CreateCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\"\\\n" +
	"\x12CreateCartResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\"O\n" +
	"\x15DeleteCartItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\"2\n" +
	"\x16DeleteCartItemResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"(\n" +
	"\rUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"4\n" +
	"\x10CartListResponse\x12 \n" +
	"\x05carts\x18\x01 \x03(\v2\n" +
	".cart.CartR\x05carts\"8\n" +
	"\x11CartItemsResponse\x12#\n" +
	"\x05items\x18\x01 \x03(\v2\r.cart.ProductR\x05items\"_\n" +
	"\x15UpdateCartItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\"Q\n" +
	"\x17HasProductInCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\";\n" +
	"\x18HasProductInCartResponse\x12\x1f\n" +
	"\vhas_product\x18\x01 \x01(\bR\n" +
	"hasProduct\"-\n" +
	"\x15CartItemCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"9\n" +
	"\x16CartTotalPriceResponse\x12\x1f\n" +
	"\vtotal_price\x18\x01 \x01(\x01R\n" +
	"totalPrice\"j\n" +
	"\x1bSendCartSummaryEmailRequest\x12\x19\n" +
	"\bto_email\x18\x01 \x01(\tR\atoEmail\x12\x17\n" +
	"\ato_name\x18\x02 \x01(\tR\x06toName\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\"C\n" +
	"\x13EmailStatusResponse\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"C\n" +
	"\rCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8f\a\n" +
	"\vCartService\x12>\n" +
	"\tAddToCart\x12\x17.cart.CreateCartRequest\x1a\x18.cart.CreateCartResponse\x12K\n" +
	"\x0eRemoveFromCart\x12\x1b.cart.DeleteCartItemRequest\x1a\x1c.cart.DeleteCartItemResponse\x128\n" +
	"\tClearCart\x12\x13.cart.UserIDRequest\x1a\x16.google.protobuf.Empty\x126\n" +
	"\aGetCart\x12\x13.cart.UserIDRequest\x1a\x16.cart.CartListResponse\x12<\n" +
	"\fGetCartItems\x12\x13.cart.UserIDRequest\x1a\x17.cart.CartItemsResponse\x12E\n" +
	"\x0eUpdateCartItem\x12\x1b.cart.UpdateCartItemRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x10HasProductInCart\x12\x1d.cart.HasProductInCartRequest\x1a\x1e.cart.HasProductInCartResponse\x12D\n" +
	"\x10GetCartItemCount\x12\x13.cart.UserIDRequest\x1a\x1b.cart.CartItemCountResponse\x12F\n" +
	"\x11GetCartTotalPrice\x12\x13.cart.UserIDRequest\x1a\x1c.cart.CartTotalPriceResponse\x12T\n" +
	"\x14SendCartSummaryEmail\x12!.cart.SendCartSummaryEmailRequest\x1a\x19.cart.EmailStatusResponse\x12?\n" +
	"\x13InvalidateCartCache\x12\x13.cart.UserIDRequest\x1a\x13.cart.CacheResponse\x12A\n" +
	"\x0fGetAllFromRedis\x12\x16.google.protobuf.Empty\x1a\x16.cart.CartListResponse\x12A\n" +
	"\x0fGetAllFromCache\x12\x16.google.protobuf.Empty\x1a\x16.cart.CartListResponseB4Z2github.com/RakhatLukum/CodeMart/cart-service/protob\x06proto3"

var (
	file_cart_proto_rawDescOnce sync.Once
	file_cart_proto_rawDescData []byte
)

func file_cart_proto_rawDescGZIP() []byte {
	file_cart_proto_rawDescOnce.Do(func() {
		file_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)))
	})
	return file_cart_proto_rawDescData
}

var file_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cart_proto_goTypes = []any{
	(*Cart)(nil),                        // 0: cart.Cart
	(*Product)(nil),                     // 1: cart.Product
	(*CreateCartRequest)(nil),           // 2: cart.CreateCartRequest
	(*CreateCartResponse)(nil),          // 3: cart.CreateCartResponse
	(*DeleteCartItemRequest)(nil),       // 4: cart.DeleteCartItemRequest
	(*DeleteCartItemResponse)(nil),      // 5: cart.DeleteCartItemResponse
	(*UserIDRequest)(nil),               // 6: cart.UserIDRequest
	(*CartListResponse)(nil),            // 7: cart.CartListResponse
	(*CartItemsResponse)(nil),           // 8: cart.CartItemsResponse
	(*UpdateCartItemRequest)(nil),       // 9: cart.UpdateCartItemRequest
	(*HasProductInCartRequest)(nil),     // 10: cart.HasProductInCartRequest
	(*HasProductInCartResponse)(nil),    // 11: cart.HasProductInCartResponse
	(*CartItemCountResponse)(nil),       // 12: cart.CartItemCountResponse
	(*CartTotalPriceResponse)(nil),      // 13: cart.CartTotalPriceResponse
	(*SendCartSummaryEmailRequest)(nil), // 14: cart.SendCartSummaryEmailRequest
	(*EmailStatusResponse)(nil),         // 15: cart.EmailStatusResponse
	(*CacheResponse)(nil),               // 16: cart.CacheResponse
	(*emptypb.Empty)(nil),               // 17: google.protobuf.Empty
}
var file_cart_proto_depIdxs = []int32{
	0,  // 0: cart.CartListResponse.carts:type_name -> cart.Cart
	1,  // 1: cart.CartItemsResponse.items:type_name -> cart.Product
	2,  // 2: cart.CartService.AddToCart:input_type -> cart.CreateCartRequest
	4,  // 3: cart.CartService.RemoveFromCart:input_type -> cart.DeleteCartItemRequest
	6,  // 4: cart.CartService.ClearCart:input_type -> cart.UserIDRequest
	6,  // 5: cart.CartService.GetCart:input_type -> cart.UserIDRequest
	6,  // 6: cart.CartService.GetCartItems:input_type -> cart.UserIDRequest
	9,  // 7: cart.CartService.UpdateCartItem:input_type -> cart.UpdateCartItemRequest
	10, // 8: cart.CartService.HasProductInCart:input_type -> cart.HasProductInCartRequest
	6,  // 9: cart.CartService.GetCartItemCount:input_type -> cart.UserIDRequest
	6,  // 10: cart.CartService.GetCartTotalPrice:input_type -> cart.UserIDRequest
	14, // 11: cart.CartService.SendCartSummaryEmail:input_type -> cart.SendCartSummaryEmailRequest
	6,  // 12: cart.CartService.InvalidateCartCache:input_type -> cart.UserIDRequest
	17, // 13: cart.CartService.GetAllFromRedis:input_type -> google.protobuf.Empty
	17, // 14: cart.CartService.GetAllFromCache:input_type -> google.protobuf.Empty
	3,  // 15: cart.CartService.AddToCart:output_type -> cart.CreateCartResponse
	5,  // 16: cart.CartService.RemoveFromCart:output_type -> cart.DeleteCartItemResponse
	17, // 17: cart.CartService.ClearCart:output_type -> google.protobuf.Empty
	7,  // 18: cart.CartService.GetCart:output_type -> cart.CartListResponse
	8,  // 19: cart.CartService.GetCartItems:output_type -> cart.CartItemsResponse
	17, // 20: cart.CartService.UpdateCartItem:output_type -> google.protobuf.Empty
	11, // 21: cart.CartService.HasProductInCart:output_type -> cart.HasProductInCartResponse
	12, // 22: cart.CartService.GetCartItemCount:output_type -> cart.CartItemCountResponse
	13, // 23: cart.CartService.GetCartTotalPrice:output_type -> cart.CartTotalPriceResponse
	15, // 24: cart.CartService.SendCartSummaryEmail:output_type -> cart.EmailStatusResponse
	16, // 25: cart.CartService.InvalidateCartCache:output_type -> cart.CacheResponse
	7,  // 26: cart.CartService.GetAllFromRedis:output_type -> cart.CartListResponse
	7,  // 27: cart.CartService.GetAllFromCache:output_type -> cart.CartListResponse
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cart_proto_init() }
func file_cart_proto_init() {
	if File_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cart_proto_rawDesc), len(file_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cart_proto_goTypes,
		DependencyIndexes: file_cart_proto_depIdxs,
		MessageInfos:      file_cart_proto_msgTypes,
	}.Build()
	File_cart_proto = out.File
	file_cart_proto_goTypes = nil
	file_cart_proto_depIdxs = nil
}
