// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/analytics.proto

package analytics_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

type CreateViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateViewRequest) Reset() {
	*x = CreateViewRequest{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewRequest) ProtoMessage() {}

func (x *CreateViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewRequest.ProtoReflect.Descriptor instead.
func (*CreateViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *CreateViewRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateViewRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type CreateViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateViewResponse) Reset() {
	*x = CreateViewResponse{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewResponse) ProtoMessage() {}

func (x *CreateViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewResponse.ProtoReflect.Descriptor instead.
func (*CreateViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *CreateViewResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateViewResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateViewResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateViewResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *UserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRequest) Reset() {
	*x = ProductRequest{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRequest) ProtoMessage() {}

func (x *ProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRequest.ProtoReflect.Descriptor instead.
func (*ProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *ProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type UserProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProductRequest) Reset() {
	*x = UserProductRequest{}
	mi := &file_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProductRequest) ProtoMessage() {}

func (x *UserProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProductRequest.ProtoReflect.Descriptor instead.
func (*UserProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *UserProductRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewResponse) Reset() {
	*x = ViewResponse{}
	mi := &file_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResponse) ProtoMessage() {}

func (x *ViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResponse.ProtoReflect.Descriptor instead.
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *ViewResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ViewResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ViewResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ViewResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type UserViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*ViewResponse        `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserViewsResponse) Reset() {
	*x = UserViewsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserViewsResponse) ProtoMessage() {}

func (x *UserViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserViewsResponse.ProtoReflect.Descriptor instead.
func (*UserViewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *UserViewsResponse) GetViews() []*ViewResponse {
	if x != nil {
		return x.Views
	}
	return nil
}

type ProductViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*ViewResponse        `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductViewsResponse) Reset() {
	*x = ProductViewsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductViewsResponse) ProtoMessage() {}

func (x *ProductViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductViewsResponse.ProtoReflect.Descriptor instead.
func (*ProductViewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *ProductViewsResponse) GetViews() []*ViewResponse {
	if x != nil {
		return x.Views
	}
	return nil
}

type UserProductViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*ViewResponse        `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProductViewsResponse) Reset() {
	*x = UserProductViewsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProductViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProductViewsResponse) ProtoMessage() {}

func (x *UserProductViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProductViewsResponse.ProtoReflect.Descriptor instead.
func (*UserProductViewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *UserProductViewsResponse) GetViews() []*ViewResponse {
	if x != nil {
		return x.Views
	}
	return nil
}

type RecentViewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentViewsRequest) Reset() {
	*x = RecentViewsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentViewsRequest) ProtoMessage() {}

func (x *RecentViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentViewsRequest.ProtoReflect.Descriptor instead.
func (*RecentViewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *RecentViewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecentViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         []*ViewResponse        `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentViewsResponse) Reset() {
	*x = RecentViewsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentViewsResponse) ProtoMessage() {}

func (x *RecentViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentViewsResponse.ProtoReflect.Descriptor instead.
func (*RecentViewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *RecentViewsResponse) GetViews() []*ViewResponse {
	if x != nil {
		return x.Views
	}
	return nil
}

type ProductViewCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ViewCount     int32                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductViewCount) Reset() {
	*x = ProductViewCount{}
	mi := &file_proto_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductViewCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductViewCount) ProtoMessage() {}

func (x *ProductViewCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductViewCount.ProtoReflect.Descriptor instead.
func (*ProductViewCount) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *ProductViewCount) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductViewCount) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type MostViewedProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductViewCount    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostViewedProductsResponse) Reset() {
	*x = MostViewedProductsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostViewedProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostViewedProductsResponse) ProtoMessage() {}

func (x *MostViewedProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostViewedProductsResponse.ProtoReflect.Descriptor instead.
func (*MostViewedProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *MostViewedProductsResponse) GetData() []*ProductViewCount {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserTopProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTopProductsRequest) Reset() {
	*x = UserTopProductsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTopProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTopProductsRequest) ProtoMessage() {}

func (x *UserTopProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTopProductsRequest.ProtoReflect.Descriptor instead.
func (*UserTopProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *UserTopProductsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserTopProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserTopProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Data          []*ProductViewCount    `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTopProductsResponse) Reset() {
	*x = UserTopProductsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTopProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTopProductsResponse) ProtoMessage() {}

func (x *UserTopProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTopProductsResponse.ProtoReflect.Descriptor instead.
func (*UserTopProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{15}
}

func (x *UserTopProductsResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserTopProductsResponse) GetData() []*ProductViewCount {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProductViewCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ViewCount     int32                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductViewCountResponse) Reset() {
	*x = ProductViewCountResponse{}
	mi := &file_proto_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductViewCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductViewCountResponse) ProtoMessage() {}

func (x *ProductViewCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductViewCountResponse.ProtoReflect.Descriptor instead.
func (*ProductViewCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *ProductViewCountResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductViewCountResponse) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type UserViewCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ViewCount     int32                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserViewCountResponse) Reset() {
	*x = UserViewCountResponse{}
	mi := &file_proto_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserViewCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserViewCountResponse) ProtoMessage() {}

func (x *UserViewCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserViewCountResponse.ProtoReflect.Descriptor instead.
func (*UserViewCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{17}
}

func (x *UserViewCountResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserViewCountResponse) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type DailyViewStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ViewCount     int32                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyViewStat) Reset() {
	*x = DailyViewStat{}
	mi := &file_proto_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyViewStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyViewStat) ProtoMessage() {}

func (x *DailyViewStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyViewStat.ProtoReflect.Descriptor instead.
func (*DailyViewStat) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *DailyViewStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyViewStat) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type DailyViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DailyViewStat       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyViewsResponse) Reset() {
	*x = DailyViewsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyViewsResponse) ProtoMessage() {}

func (x *DailyViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyViewsResponse.ProtoReflect.Descriptor instead.
func (*DailyViewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{19}
}

func (x *DailyViewsResponse) GetData() []*DailyViewStat {
	if x != nil {
		return x.Data
	}
	return nil
}

type HourlyViewStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          int32                  `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	ViewCount     int32                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HourlyViewStat) Reset() {
	*x = HourlyViewStat{}
	mi := &file_proto_analytics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourlyViewStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourlyViewStat) ProtoMessage() {}

func (x *HourlyViewStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourlyViewStat.ProtoReflect.Descriptor instead.
func (*HourlyViewStat) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{20}
}

func (x *HourlyViewStat) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *HourlyViewStat) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type HourlyViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Data          []*HourlyViewStat      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HourlyViewsResponse) Reset() {
	*x = HourlyViewsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourlyViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourlyViewsResponse) ProtoMessage() {}

func (x *HourlyViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourlyViewsResponse.ProtoReflect.Descriptor instead.
func (*HourlyViewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{21}
}

func (x *HourlyViewsResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *HourlyViewsResponse) GetData() []*HourlyViewStat {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReportEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEmailRequest) Reset() {
	*x = ReportEmailRequest{}
	mi := &file_proto_analytics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEmailRequest) ProtoMessage() {}

func (x *ReportEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEmailRequest.ProtoReflect.Descriptor instead.
func (*ReportEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{22}
}

func (x *ReportEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReportEmailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReportEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEmailResponse) Reset() {
	*x = ReportEmailResponse{}
	mi := &file_proto_analytics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEmailResponse) ProtoMessage() {}

func (x *ReportEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEmailResponse.ProtoReflect.Descriptor instead.
func (*ReportEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{23}
}

func (x *ReportEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteOldViewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOldViewsRequest) Reset() {
	*x = DeleteOldViewsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOldViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOldViewsRequest) ProtoMessage() {}

func (x *DeleteOldViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOldViewsRequest.ProtoReflect.Descriptor instead.
func (*DeleteOldViewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteOldViewsRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type DeleteOldViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOldViewsResponse) Reset() {
	*x = DeleteOldViewsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOldViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOldViewsResponse) ProtoMessage() {}

func (x *DeleteOldViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOldViewsResponse.ProtoReflect.Descriptor instead.
func (*DeleteOldViewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteOldViewsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\x04view\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"K\n" +
	"\x11CreateViewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\"\x96\x01\n" +
	"\x12CreateViewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"/\n" +
	"\x0eProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\"L\n" +
	"\x12UserProductRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\"\x90\x01\n" +
	"\fViewResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"=\n" +
	"\x11UserViewsResponse\x12(\n" +
	"\x05views\x18\x01 \x03(\v2\x12.view.ViewResponseR\x05views\"@\n" +
	"\x14ProductViewsResponse\x12(\n" +
	"\x05views\x18\x01 \x03(\v2\x12.view.ViewResponseR\x05views\"D\n" +
	"\x18UserProductViewsResponse\x12(\n" +
	"\x05views\x18\x01 \x03(\v2\x12.view.ViewResponseR\x05views\"*\n" +
	"\x12RecentViewsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"?\n" +
	"\x13RecentViewsResponse\x12(\n" +
	"\x05views\x18\x01 \x03(\v2\x12.view.ViewResponseR\x05views\"P\n" +
	"\x10ProductViewCount\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x05R\tviewCount\"H\n" +
	"\x1aMostViewedProductsResponse\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.view.ProductViewCountR\x04data\"G\n" +
	"\x16UserTopProductsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"^\n" +
	"\x17UserTopProductsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12*\n" +
	"\x04data\x18\x02 \x03(\v2\x16.view.ProductViewCountR\x04data\"X\n" +
	"\x18ProductViewCountResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x05R\tviewCount\"O\n" +
	"\x15UserViewCountResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x05R\tviewCount\"B\n" +
	"\rDailyViewStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x05R\tviewCount\"=\n" +
	"\x12DailyViewsResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.view.DailyViewStatR\x04data\"C\n" +
	"\x0eHourlyViewStat\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x05R\tviewCount\"^\n" +
	"\x13HourlyViewsResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12(\n" +
	"\x04data\x18\x02 \x03(\v2\x14.view.HourlyViewStatR\x04data\">\n" +
	"\x12ReportEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\x13ReportEmailResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"K\n" +
	"\x15DeleteOldViewsRequest\x122\n" +
	"\x06before\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\"=\n" +
	"\x16DeleteOldViewsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount2\xb5\b\n" +
	"\vViewService\x12?\n" +
	"\n" +
	"CreateView\x12\x17.view.CreateViewRequest\x1a\x18.view.CreateViewResponse\x12<\n" +
	"\x0eGetViewsByUser\x12\x11.view.UserRequest\x1a\x17.view.UserViewsResponse\x12E\n" +
	"\x11GetViewsByProduct\x12\x14.view.ProductRequest\x1a\x1a.view.ProductViewsResponse\x12T\n" +
	"\x18GetViewsByUserAndProduct\x12\x18.view.UserProductRequest\x1a\x1e.view.UserProductViewsResponse\x12E\n" +
	"\x0eGetRecentViews\x12\x18.view.RecentViewsRequest\x1a\x19.view.RecentViewsResponse\x12F\n" +
	"\x15GetMostViewedProducts\x12\v.view.Empty\x1a .view.MostViewedProductsResponse\x12Q\n" +
	"\x12GetUserTopProducts\x12\x1c.view.UserTopProductsRequest\x1a\x1d.view.UserTopProductsResponse\x12K\n" +
	"\x13GetProductViewCount\x12\x14.view.ProductRequest\x1a\x1e.view.ProductViewCountResponse\x12B\n" +
	"\x10GetUserViewCount\x12\x11.view.UserRequest\x1a\x1b.view.UserViewCountResponse\x126\n" +
	"\rGetDailyViews\x12\v.view.Empty\x1a\x18.view.DailyViewsResponse\x12S\n" +
	"\x1cGenerateDailyViewReportEmail\x12\x18.view.ReportEmailRequest\x1a\x19.view.ReportEmailResponse\x12A\n" +
	"\x0eGetHourlyViews\x12\x14.view.ProductRequest\x1a\x19.view.HourlyViewsResponse\x12K\n" +
	"\x0eDeleteOldViews\x12\x1b.view.DeleteOldViewsRequest\x1a\x1c.view.DeleteOldViewsResponse\x129\n" +
	"\rGetCachedView\x12\x14.view.ProductRequest\x1a\x12.view.ViewResponse\x12?\n" +
	"\x13GetMemoryCachedView\x12\x14.view.ProductRequest\x1a\x12.view.ViewResponseB3Z1github.com/RakhatLukum/CodeMart/analytics-serviceb\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_analytics_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: view.Empty
	(*CreateViewRequest)(nil),          // 1: view.CreateViewRequest
	(*CreateViewResponse)(nil),         // 2: view.CreateViewResponse
	(*UserRequest)(nil),                // 3: view.UserRequest
	(*ProductRequest)(nil),             // 4: view.ProductRequest
	(*UserProductRequest)(nil),         // 5: view.UserProductRequest
	(*ViewResponse)(nil),               // 6: view.ViewResponse
	(*UserViewsResponse)(nil),          // 7: view.UserViewsResponse
	(*ProductViewsResponse)(nil),       // 8: view.ProductViewsResponse
	(*UserProductViewsResponse)(nil),   // 9: view.UserProductViewsResponse
	(*RecentViewsRequest)(nil),         // 10: view.RecentViewsRequest
	(*RecentViewsResponse)(nil),        // 11: view.RecentViewsResponse
	(*ProductViewCount)(nil),           // 12: view.ProductViewCount
	(*MostViewedProductsResponse)(nil), // 13: view.MostViewedProductsResponse
	(*UserTopProductsRequest)(nil),     // 14: view.UserTopProductsRequest
	(*UserTopProductsResponse)(nil),    // 15: view.UserTopProductsResponse
	(*ProductViewCountResponse)(nil),   // 16: view.ProductViewCountResponse
	(*UserViewCountResponse)(nil),      // 17: view.UserViewCountResponse
	(*DailyViewStat)(nil),              // 18: view.DailyViewStat
	(*DailyViewsResponse)(nil),         // 19: view.DailyViewsResponse
	(*HourlyViewStat)(nil),             // 20: view.HourlyViewStat
	(*HourlyViewsResponse)(nil),        // 21: view.HourlyViewsResponse
	(*ReportEmailRequest)(nil),         // 22: view.ReportEmailRequest
	(*ReportEmailResponse)(nil),        // 23: view.ReportEmailResponse
	(*DeleteOldViewsRequest)(nil),      // 24: view.DeleteOldViewsRequest
	(*DeleteOldViewsResponse)(nil),     // 25: view.DeleteOldViewsResponse
	(*timestamppb.Timestamp)(nil),      // 26: google.protobuf.Timestamp
}
var file_proto_analytics_proto_depIdxs = []int32{
	26, // 0: view.CreateViewResponse.timestamp:type_name -> google.protobuf.Timestamp
	26, // 1: view.ViewResponse.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 2: view.UserViewsResponse.views:type_name -> view.ViewResponse
	6,  // 3: view.ProductViewsResponse.views:type_name -> view.ViewResponse
	6,  // 4: view.UserProductViewsResponse.views:type_name -> view.ViewResponse
	6,  // 5: view.RecentViewsResponse.views:type_name -> view.ViewResponse
	12, // 6: view.MostViewedProductsResponse.data:type_name -> view.ProductViewCount
	12, // 7: view.UserTopProductsResponse.data:type_name -> view.ProductViewCount
	18, // 8: view.DailyViewsResponse.data:type_name -> view.DailyViewStat
	20, // 9: view.HourlyViewsResponse.data:type_name -> view.HourlyViewStat
	26, // 10: view.DeleteOldViewsRequest.before:type_name -> google.protobuf.Timestamp
	1,  // 11: view.ViewService.CreateView:input_type -> view.CreateViewRequest
	3,  // 12: view.ViewService.GetViewsByUser:input_type -> view.UserRequest
	4,  // 13: view.ViewService.GetViewsByProduct:input_type -> view.ProductRequest
	5,  // 14: view.ViewService.GetViewsByUserAndProduct:input_type -> view.UserProductRequest
	10, // 15: view.ViewService.GetRecentViews:input_type -> view.RecentViewsRequest
	0,  // 16: view.ViewService.GetMostViewedProducts:input_type -> view.Empty
	14, // 17: view.ViewService.GetUserTopProducts:input_type -> view.UserTopProductsRequest
	4,  // 18: view.ViewService.GetProductViewCount:input_type -> view.ProductRequest
	3,  // 19: view.ViewService.GetUserViewCount:input_type -> view.UserRequest
	0,  // 20: view.ViewService.GetDailyViews:input_type -> view.Empty
	22, // 21: view.ViewService.GenerateDailyViewReportEmail:input_type -> view.ReportEmailRequest
	4,  // 22: view.ViewService.GetHourlyViews:input_type -> view.ProductRequest
	24, // 23: view.ViewService.DeleteOldViews:input_type -> view.DeleteOldViewsRequest
	4,  // 24: view.ViewService.GetCachedView:input_type -> view.ProductRequest
	4,  // 25: view.ViewService.GetMemoryCachedView:input_type -> view.ProductRequest
	2,  // 26: view.ViewService.CreateView:output_type -> view.CreateViewResponse
	7,  // 27: view.ViewService.GetViewsByUser:output_type -> view.UserViewsResponse
	8,  // 28: view.ViewService.GetViewsByProduct:output_type -> view.ProductViewsResponse
	9,  // 29: view.ViewService.GetViewsByUserAndProduct:output_type -> view.UserProductViewsResponse
	11, // 30: view.ViewService.GetRecentViews:output_type -> view.RecentViewsResponse
	13, // 31: view.ViewService.GetMostViewedProducts:output_type -> view.MostViewedProductsResponse
	15, // 32: view.ViewService.GetUserTopProducts:output_type -> view.UserTopProductsResponse
	16, // 33: view.ViewService.GetProductViewCount:output_type -> view.ProductViewCountResponse
	17, // 34: view.ViewService.GetUserViewCount:output_type -> view.UserViewCountResponse
	19, // 35: view.ViewService.GetDailyViews:output_type -> view.DailyViewsResponse
	23, // 36: view.ViewService.GenerateDailyViewReportEmail:output_type -> view.ReportEmailResponse
	21, // 37: view.ViewService.GetHourlyViews:output_type -> view.HourlyViewsResponse
	25, // 38: view.ViewService.DeleteOldViews:output_type -> view.DeleteOldViewsResponse
	6,  // 39: view.ViewService.GetCachedView:output_type -> view.ViewResponse
	6,  // 40: view.ViewService.GetMemoryCachedView:output_type -> view.ViewResponse
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
